[tool.poetry]
name = "genmus"
version = "0.1.0"
description = "genmus: Plays DNA in piano from a FASTA file."
authors = ["Oliver Bonham-Carter <obonhamcarter@allegheny.edu>"]
readme = "README.md"

[tool.poetry.scripts]
genmus = "genmus.main:cli"

[tool.poetry.dependencies]
#python = ">=3.10,<3.12" #working
python = ">=3.8,<3.12"
scipy = "1.9.1"
rich = "^12.6.0"
typer = "^0.6.1"
biopython = "^1.79"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
mypy = "^0.982"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
